services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: LibraryApp/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=LibraryDB111;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

  frontend:
    build:
      context: .
      dockerfile: library-ui/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mssql_data: