version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql 
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 30  

  backend:
    build:
      context: .
      dockerfile: LibraryApp/Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      db:
        condition: service_healthy  
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=LibraryDB111;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Production"  
      ASPNETCORE_URLS: "http://+:80" 

  frontend:
    build:
      context: .
      dockerfile: library-ui/Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      backend:
        condition: service_healthy  

volumes:
  mssql_data: